### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Hugoyhu**
It's not a "leodardo" board nor a "leonardo" it's based off Arduino compatible Pro micro

Please review

### CODE REVIEW

**Comment by sampoder** [comment]
hi Hugo

**Comment by MatthewStanciu** [comment]
Lol for a sec I thought this was a hacktoberfest spam pr

**Comment by Hugoyhu** [comment]
I’m offended you’d think I’m a scammer



On Oct 2, 2020, at 11:16 AM, Matthew Stanciu <notifications@github.com<mailto:notifications@github.com>> wrote:



Lol for a sec I thought this was a hacktoberfest spam pr

**Comment by MatthewStanciu** [comment]
yeah every day i come into work and i think "damn, that scammer hugo, i wonder whaat that scammer hugo is scamming us with today"

**Comment by Hugoyhu** [comment]
oh my

On Oct 2, 2020, at 11:19 AM, Matthew Stanciu <notifications@github.com<mailto:notifications@github.com>> wrote:



yeah every day i come into work and i think "damn, that scammer hugo, i wonder whaat that scammer hugo is scamming us with today"

**Comment by MatthewStanciu** [comment]
@sampoder thoughts?

**Comment by Hugoyhu** [comment]
1) what’s commit
2) what’s happening
3) why so many commits


On Oct 2, 2020, at 11:23 AM, Matthew Stanciu <notifications@github.com<mailto:notifications@github.com>> wrote:



@sampoder<https://github.com/sampoder> thoughts?

**Comment by MatthewStanciu** [comment]
they call me the commit man bceause i commit so much

**Comment by Hugoyhu** [comment]
WHAT IS A COMMIT THOUGH

On Oct 2, 2020, at 11:27 AM, Matthew Stanciu <notifications@github.com<mailto:notifications@github.com>> wrote:



they call me the commit man bceause i commit so much

**Comment by sampoder** [comment]
I guess I shall merge, if Kevin complains not my fault lol scammer Hugo

**Comment by sampoder** [comment]
this is a great thread ngl

**Comment by sampoder** [comment]
also in the meantime anyone know when grammarly is coming to vscode?

**Comment by Hugoyhu** [comment]
I’m just replying by email don’t mind me

what is a commit

how is good thread lmao


On Oct 2, 2020, at 11:31 AM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



this is a great thread ngl

**Comment by sampoder** [comment]
a commit is when you change smth, like a code change

**Comment by Hugoyhu** [comment]
but didn’t I do a pull reuqest

On Oct 2, 2020, at 11:39 AM, Sam Poder <notifications@github.com<mailto:notifications@github.com>> wrote:



a commit is when you change smth, like a code change

**Comment by sampoder** [comment]
a pull request is a collection of commits

**Comment by Hugoyhu** [comment]
oh ok

**Pull request merged**
